export interface ComunaPoint {
  name: string;
  address: string;
  materials: string;
  type: "Público" | "Privado";
}

export const comunaPoints: Record<string, ComunaPoint[]> = {
  "Santiago": [
    { name: "Centro de Reciclaje Santiago", address: "Av. Libertador Bernardo O'Higgins 123", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoPlast Santiago", address: "Calle San Antonio 456", materials: "Plástico, Vidrio", type: "Privado" },
    { name: "Punto Verde Alameda", address: "Alameda 2500", materials: "Papel, Cartón", type: "Público" },
    { name: "Reciclaje Electrónico Santiago", address: "Calle Estado 111", materials: "Electrónicos", type: "Privado" },
    { name: "Recicla Metropolitana", address: "Av. Matta 1400", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoCenter Santiago", address: "Calle Huérfanos 890", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "Punto Limpio Santiago Centro", address: "Av. Libertador Bernardo O'Higgins 1750", materials: "Plástico, Metal", type: "Público" },
    { name: "GreenPoint Santiago", address: "Calle San Diego 1200", materials: "Plástico, Papel", type: "Privado" },
    { name: "EcoAlameda", address: "Av. Alameda 3000", materials: "Papel, Cartón, Electrónicos", type: "Público" },
    { name: "ReciReciclaje", address: "Calle Bandera 550", materials: "Plástico, Vidrio", type: "Privado" },
  ],
  "Providencia": [
    { name: "Reciclaje Providencia", address: "Av. Providencia 2222", materials: "Papel, Cartón, Electrónicos", type: "Público" },
    { name: "GreenPoint Providencia", address: "Calle Los Leones 1111", materials: "Plástico, Metal", type: "Privado" },
    { name: "EcoCentro Providencia", address: "Av. Manuel Montt 999", materials: "Vidrio, Plástico", type: "Público" },
    { name: "Punto Limpio Providencia", address: "Av. Pedro de Valdivia 2100", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "ReciclaTech Providencia", address: "Calle José Miguel Claro 1234", materials: "Electrónicos", type: "Privado" },
    { name: "Centro Verde Providencia", address: "Av. Luis Thayer Ojeda 1500", materials: "Papel, Cartón", type: "Público" },
    { name: "EcoPlaza Providencia", address: "Av. Providencia 3000", materials: "Plástico, Vidrio", type: "Privado" },
    { name: "ReciPlus Providencia", address: "Calle Miguel Claro 2100", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Verde Las Lilas", address: "Av. Providencia 3600", materials: "Plástico, Metal", type: "Privado" },
    { name: "EcoRecicla Providencia", address: "Calle Pedro de Valdivia 1980", materials: "Electrónicos", type: "Público" },
  ],
  "Las Condes": [
    { name: "Centro Verde Las Condes", address: "Av. Apoquindo 5000", materials: "Papel, Cartón, Electrónicos", type: "Público" },
    { name: "Recicla Plus", address: "Calle Cerro El Plomo 777", materials: "Plástico, Vidrio", type: "Privado" },
    { name: "Punto Limpio Las Condes", address: "Av. Las Condes 5800", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoCenter Las Condes", address: "Av. Kennedy 9000", materials: "Vidrio, Metal", type: "Privado" },
    { name: "GreenPoint Apoquindo", address: "Calle Apoquindo 6000", materials: "Plástico, Papel", type: "Público" },
    { name: "ReciLas Condes", address: "Av. Manquehue 1400", materials: "Papel, Cartón", type: "Privado" },
    { name: "Centro Reciclaje Lo Barnechea", address: "Av. La Dehesa 8000", materials: "Electrónicos", type: "Público" },
    { name: "EcoPlaza Las Condes", address: "Av. Las Condes 7200", materials: "Plástico, Vidrio", type: "Privado" },
    { name: "Punto Limpio Manquehue", address: "Av. Manquehue 1500", materials: "Papel, Cartón", type: "Público" },
    { name: "ReciclaTech Las Condes", address: "Calle El Rodeo 1000", materials: "Electrónicos, Plástico", type: "Privado" },
  ],
  "Maipú": [
    { name: "EcoMaipú", address: "Calle 5 de Abril 1500", materials: "Plástico, Vidrio, Metal", type: "Público" },
    { name: "ReciMaipú", address: "Av. Pajaritos 333", materials: "Papel, Cartón", type: "Privado" },
    { name: "Punto Limpio Maipú", address: "Av. Central 2100", materials: "Plástico, Vidrio", type: "Público" },
    { name: "Recicla Maipú", address: "Calle Camilo Henríquez 4400", materials: "Papel, Cartón", type: "Público" },
    { name: "EcoCentro Maipú", address: "Av. Vicuña Mackenna 8900", materials: "Plástico, Vidrio", type: "Privado" },
    { name: "ReciPlus Maipú", address: "Calle 1 Sur 1200", materials: "Electrónicos", type: "Público" },
    { name: "Centro Verde Maipú", address: "Av. 5 de Abril 1900", materials: "Plástico, Metal", type: "Público" },
    { name: "GreenPoint Maipú", address: "Av. Pajaritos 555", materials: "Papel, Cartón", type: "Privado" },
    { name: "EcoRecicla Maipú", address: "Av. 5 de Abril 1600", materials: "Plástico, Vidrio", type: "Público" },
    { name: "Punto Limpio Central Maipú", address: "Calle Cerro Maipú 800", materials: "Electrónicos", type: "Privado" },
  ],
  "Ñuñoa": [
    { name: "Centro de Reciclaje Ñuñoa", address: "Av. Irarrázabal 3500", materials: "Papel, Cartón", type: "Público" },
    { name: "GreenEco Ñuñoa", address: "Calle Jorge Washington 1111", materials: "Plástico, Metal", type: "Privado" },
    { name: "Punto Limpio Ñuñoa", address: "Av. Pedro de Valdivia 4500", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "Recicla Ñuñoa", address: "Av. Grecia 1800", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "EcoPlaza Ñuñoa", address: "Calle Bilbao 1200", materials: "Papel, Cartón", type: "Público" },
    { name: "ReciCenter Ñuñoa", address: "Av. Irarrázabal 3000", materials: "Electrónicos", type: "Privado" },
    { name: "EcoRecicla Ñuñoa", address: "Av. Irarrázabal 3600", materials: "Plástico, Metal", type: "Público" },
    { name: "Punto Verde Ñuñoa", address: "Calle Pedro de Valdivia 4200", materials: "Plástico, Vidrio", type: "Privado" },
    { name: "Centro Limpio Ñuñoa", address: "Av. Grecia 2000", materials: "Papel, Cartón", type: "Público" },
    { name: "ReciÑuñoa", address: "Calle Jorge Washington 1500", materials: "Electrónicos", type: "Privado" },
  ],
  "La Florida": [
    { name: "Punto Limpio La Florida", address: "Av. Vicuña Mackenna 6000", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoRecicla La Florida", address: "Calle Las Torres 1234", materials: "Electrónicos, Plástico", type: "Privado" },
    { name: "Centro Verde La Florida", address: "Av. Américo Vespucio 7800", materials: "Papel, Cartón", type: "Público" },
    { name: "GreenPoint La Florida", address: "Calle José Joaquín Prieto 2100", materials: "Plástico, Metal", type: "Privado" },
    { name: "ReciPlus La Florida", address: "Av. Vicuña Mackenna 6700", materials: "Vidrio, Plástico", type: "Público" },
    { name: "EcoCentro La Florida", address: "Calle Trinidad 1100", materials: "Papel, Cartón, Electrónicos", type: "Privado" },
    { name: "Punto Limpio Plaza La Florida", address: "Av. Vicuña Mackenna 6300", materials: "Papel, Cartón", type: "Público" },
    { name: "ReciclajeTech La Florida", address: "Calle Camino Real 4400", materials: "Electrónicos", type: "Privado" },
    { name: "EcoPlaza La Florida", address: "Av. Macul 5000", materials: "Plástico, Vidrio", type: "Público" },
    { name: "Punto Verde La Florida", address: "Calle Las Rosas 2300", materials: "Plástico, Metal", type: "Privado" },
  ],
  "Puente Alto": [
    { name: "Punto Limpio Puente Alto", address: "Av. Concha y Toro 900", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoCentro Puente Alto", address: "Calle Gabriela 1200", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "ReciPlus Puente Alto", address: "Av. Estanislao del Campo 1500", materials: "Electrónicos", type: "Público" },
    { name: "Centro Verde Puente Alto", address: "Calle Domingo Santa María 200", materials: "Papel, Cartón", type: "Público" },
    { name: "GreenPoint Puente Alto", address: "Av. Gabriela 1800", materials: "Plástico, Metal", type: "Privado" },
    { name: "ReciclaTech Puente Alto", address: "Calle Salvador Allende 2100", materials: "Electrónicos, Plástico", type: "Público" },
    { name: "EcoPlaza Puente Alto", address: "Av. Concha y Toro 1200", materials: "Papel, Cartón", type: "Privado" },
    { name: "Punto Verde Puente Alto", address: "Calle La Rosa 800", materials: "Vidrio, Plástico", type: "Público" },
    { name: "ReciCentro Puente Alto", address: "Av. Concha y Toro 1600", materials: "Papel, Cartón, Electrónicos", type: "Privado" },
    { name: "EcoRecicla Puente Alto", address: "Calle Carlos Valdovinos 1000", materials: "Plástico, Metal", type: "Público" },
  ],
  "Peñalolén": [
    { name: "Centro Reciclaje Peñalolén", address: "Av. Grecia 9000", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "Punto Limpio Peñalolén", address: "Calle El Peral 1200", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "EcoPlaza Peñalolén", address: "Av. Las Parcelas 1500", materials: "Papel, Cartón", type: "Público" },
    { name: "GreenPoint Peñalolén", address: "Calle Los Alerces 800", materials: "Plástico, Metal", type: "Privado" },
    { name: "ReciPlus Peñalolén", address: "Av. Ñuñoa 7800", materials: "Electrónicos", type: "Público" },
    { name: "EcoCentro Peñalolén", address: "Calle Los Cipreses 1100", materials: "Papel, Cartón, Electrónicos", type: "Privado" },
    { name: "Punto Verde Peñalolén", address: "Av. La Florida 4400", materials: "Plástico, Vidrio", type: "Público" },
    { name: "ReciclaTech Peñalolén", address: "Calle Camino El Alba 200", materials: "Electrónicos", type: "Privado" },
    { name: "EcoRecicla Peñalolén", address: "Av. Los Presidentes 5200", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Limpio Los Nogales", address: "Calle Los Nogales 900", materials: "Plástico, Metal", type: "Privado" },
  ],
  "Quilicura": [
    { name: "Punto Limpio Quilicura", address: "Av. Los Libertadores 8000", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoCentro Quilicura", address: "Calle La Montaña 200", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "GreenPoint Quilicura", address: "Av. Lo Marcoleta 4000", materials: "Plástico, Metal", type: "Público" },
    { name: "Reciclaje Quilicura", address: "Calle Los Nogales 1100", materials: "Papel, Cartón", type: "Privado" },
    { name: "ReciPlus Quilicura", address: "Av. Conjunto 123", materials: "Electrónicos", type: "Público" },
    { name: "EcoPlaza Quilicura", address: "Calle Los Copihues 800", materials: "Papel, Cartón", type: "Privado" },
    { name: "Punto Verde Quilicura", address: "Av. La Montaña 1500", materials: "Plástico, Vidrio", type: "Público" },
    { name: "Centro Verde Quilicura", address: "Calle La Colina 900", materials: "Papel, Cartón, Electrónicos", type: "Privado" },
    { name: "ReciCentro Quilicura", address: "Av. Lo Marcoleta 5000", materials: "Plástico, Metal", type: "Público" },
    { name: "EcoRecicla Quilicura", address: "Calle Los Copihues 1200", materials: "Electrónicos", type: "Privado" },
  ],
  "Huechuraba": [
    { name: "Punto Limpio Huechuraba", address: "Av. La Pirámide 900", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoCentro Huechuraba", address: "Calle Américo Vespucio 3200", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "ReciPlus Huechuraba", address: "Av. Recoleta 1500", materials: "Electrónicos", type: "Público" },
    { name: "Centro Verde Huechuraba", address: "Calle Las Mercedes 800", materials: "Papel, Cartón", type: "Público" },
    { name: "GreenPoint Huechuraba", address: "Av. La Pirámide 1400", materials: "Plástico, Metal", type: "Privado" },
    { name: "EcoPlaza Huechuraba", address: "Calle Los Aromos 1200", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Verde Huechuraba", address: "Av. La Aurora 2200", materials: "Plástico, Vidrio", type: "Privado" },
    { name: "Reciclaje Tech Huechuraba", address: "Calle Las Torres 1100", materials: "Electrónicos", type: "Público" },
    { name: "EcoRecicla Huechuraba", address: "Av. Recoleta 1700", materials: "Papel, Cartón", type: "Privado" },
    { name: "Punto Limpio La Pirámide", address: "Av. La Pirámide 2000", materials: "Plástico, Metal", type: "Público" },
  ],
  "Renca": [
    { name: "Punto Limpio Renca", address: "Av. O'Higgins 3500", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoCentro Renca", address: "Calle La Montaña 1100", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "GreenPoint Renca", address: "Av. El Cerro 900", materials: "Plástico, Metal", type: "Público" },
    { name: "ReciPlus Renca", address: "Calle Los Robles 1500", materials: "Electrónicos", type: "Privado" },
    { name: "EcoRecicla Renca", address: "Av. El Cerro 1200", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Verde Renca", address: "Calle La Estrella 800", materials: "Plástico, Vidrio", type: "Privado" },
    { name: "Centro Verde Renca", address: "Av. O'Higgins 3700", materials: "Papel, Cartón, Electrónicos", type: "Público" },
    { name: "ReciCentro Renca", address: "Calle Los Alerces 900", materials: "Plástico, Metal", type: "Privado" },
    { name: "EcoPlaza Renca", address: "Av. El Cerro 1400", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Limpio Los Nogales", address: "Calle Los Nogales 1000", materials: "Electrónicos", type: "Privado" },
  ],
  "Lo Prado": [
    { name: "Punto Limpio Lo Prado", address: "Av. Lo Prado 2000", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoCentro Lo Prado", address: "Calle La Montaña 400", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "GreenPoint Lo Prado", address: "Av. San Pablo 3100", materials: "Plástico, Metal", type: "Público" },
    { name: "ReciPlus Lo Prado", address: "Calle Los Aromos 900", materials: "Electrónicos", type: "Privado" },
    { name: "EcoRecicla Lo Prado", address: "Av. Lo Prado 2500", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Verde Lo Prado", address: "Calle Las Torres 1200", materials: "Plástico, Vidrio", type: "Privado" },
    { name: "Centro Verde Lo Prado", address: "Av. San Pablo 3200", materials: "Papel, Cartón, Electrónicos", type: "Público" },
    { name: "ReciCentro Lo Prado", address: "Calle Los Olmos 600", materials: "Plástico, Metal", type: "Privado" },
    { name: "EcoPlaza Lo Prado", address: "Av. Lo Prado 2700", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Limpio Los Nogales", address: "Calle Los Nogales 800", materials: "Electrónicos", type: "Privado" },
  ],
  "Lo Barnechea": [
    { name: "Centro Verde Lo Barnechea", address: "Av. La Dehesa 7500", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoPlaza Lo Barnechea", address: "Calle Camino El Alba 1800", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "GreenPoint Lo Barnechea", address: "Av. La Dehesa 7700", materials: "Plástico, Metal", type: "Público" },
    { name: "ReciPlus Lo Barnechea", address: "Calle Cerro Colorado 900", materials: "Electrónicos", type: "Privado" },
    { name: "EcoRecicla Lo Barnechea", address: "Av. La Dehesa 8000", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Verde Lo Barnechea", address: "Calle El Rodeo 1100", materials: "Plástico, Vidrio", type: "Privado" },
    { name: "Centro Limpio Lo Barnechea", address: "Av. La Dehesa 8200", materials: "Papel, Cartón, Electrónicos", type: "Público" },
    { name: "ReciCentro Lo Barnechea", address: "Calle Las Tranqueras 700", materials: "Plástico, Metal", type: "Privado" },
    { name: "EcoPlaza La Dehesa", address: "Av. La Dehesa 8400", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Limpio Camino El Alba", address: "Calle Camino El Alba 2000", materials: "Electrónicos", type: "Privado" },
  ],
  "Vitacura": [
    { name: "Centro Verde Vitacura", address: "Av. Vitacura 8000", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoPlaza Vitacura", address: "Calle Los Abedules 1100", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "GreenPoint Vitacura", address: "Av. Vitacura 8100", materials: "Plástico, Metal", type: "Público" },
    { name: "ReciPlus Vitacura", address: "Calle Los Trapenses 900", materials: "Electrónicos", type: "Privado" },
    { name: "EcoRecicla Vitacura", address: "Av. Vitacura 8300", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Verde Vitacura", address: "Calle Los Abedules 1300", materials: "Plástico, Vidrio", type: "Privado" },
    { name: "Centro Limpio Vitacura", address: "Av. Vitacura 8500", materials: "Papel, Cartón, Electrónicos", type: "Público" },
    { name: "ReciCentro Vitacura", address: "Calle Los Trapenses 1100", materials: "Plástico, Metal", type: "Privado" },
    { name: "EcoPlaza Vitacura 2", address: "Av. Vitacura 8600", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Limpio Los Abedules", address: "Calle Los Abedules 1500", materials: "Electrónicos", type: "Privado" },
  ],
  "Independencia": [
    { name: "Punto Limpio Independencia", address: "Av. General Bustamante 1200", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoCentro Independencia", address: "Calle Independencia 1500", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "GreenPoint Independencia", address: "Av. Santa María 900", materials: "Plástico, Metal", type: "Público" },
    { name: "ReciPlus Independencia", address: "Calle Ejército 1200", materials: "Electrónicos", type: "Privado" },
    { name: "EcoRecicla Independencia", address: "Av. Independencia 1300", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Verde Independencia", address: "Calle General Mackenna 800", materials: "Plástico, Vidrio", type: "Privado" },
    { name: "Centro Verde Independencia", address: "Av. General Bustamante 1400", materials: "Papel, Cartón, Electrónicos", type: "Público" },
    { name: "ReciCentro Independencia", address: "Calle Ejército 1500", materials: "Plástico, Metal", type: "Privado" },
    { name: "EcoPlaza Independencia", address: "Av. Santa María 1100", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Limpio General Bustamante", address: "Calle General Bustamante 1600", materials: "Electrónicos", type: "Privado" },
  ],
  "Recoleta": [
    { name: "Punto Limpio Recoleta", address: "Av. Recoleta 1800", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoCentro Recoleta", address: "Calle Pedro Aguirre Cerda 1100", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "GreenPoint Recoleta", address: "Av. Independencia 1200", materials: "Plástico, Metal", type: "Público" },
    { name: "ReciPlus Recoleta", address: "Calle Manuel Rodríguez 900", materials: "Electrónicos", type: "Privado" },
    { name: "EcoRecicla Recoleta", address: "Av. Recoleta 1900", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Verde Recoleta", address: "Calle General Bustamante 800", materials: "Plástico, Vidrio", type: "Privado" },
    { name: "Centro Verde Recoleta", address: "Av. Independencia 1500", materials: "Papel, Cartón, Electrónicos", type: "Público" },
    { name: "ReciCentro Recoleta", address: "Calle Ejército 1000", materials: "Plástico, Metal", type: "Privado" },
    { name: "EcoPlaza Recoleta", address: "Av. Recoleta 2000", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Limpio Ejército", address: "Calle Ejército 1200", materials: "Electrónicos", type: "Privado" },
  ],
  "La Granja": [
    { name: "Punto Limpio La Granja", address: "Av. Santa Rosa 4500", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoCentro La Granja", address: "Calle La Florida 1300", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "GreenPoint La Granja", address: "Av. Santa Rosa 4600", materials: "Plástico, Metal", type: "Público" },
    { name: "ReciPlus La Granja", address: "Calle La Granja 900", materials: "Electrónicos", type: "Privado" },
    { name: "EcoRecicla La Granja", address: "Av. Santa Rosa 4700", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Verde La Granja", address: "Calle San Jorge 800", materials: "Plástico, Vidrio", type: "Privado" },
    { name: "Centro Verde La Granja", address: "Av. Santa Rosa 4800", materials: "Papel, Cartón, Electrónicos", type: "Público" },
    { name: "ReciCentro La Granja", address: "Calle La Granja 1000", materials: "Plástico, Metal", type: "Privado" },
    { name: "EcoPlaza La Granja", address: "Av. Santa Rosa 4900", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Limpio San Jorge", address: "Calle San Jorge 1200", materials: "Electrónicos", type: "Privado" },
  ],
  "Macul": [
    { name: "Punto Limpio Macul", address: "Av. Vicuña Mackenna 5200", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoCentro Macul", address: "Calle Macul 1200", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "GreenPoint Macul", address: "Av. Grecia 5000", materials: "Plástico, Metal", type: "Público" },
    { name: "ReciPlus Macul", address: "Calle San Eugenio 900", materials: "Electrónicos", type: "Privado" },
    { name: "EcoRecicla Macul", address: "Av. Vicuña Mackenna 5300", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Verde Macul", address: "Calle Macul 1500", materials: "Plástico, Vidrio", type: "Privado" },
    { name: "Centro Verde Macul", address: "Av. Grecia 5200", materials: "Papel, Cartón, Electrónicos", type: "Público" },
    { name: "ReciCentro Macul", address: "Calle San Eugenio 1200", materials: "Plástico, Metal", type: "Privado" },
    { name: "EcoPlaza Macul", address: "Av. Vicuña Mackenna 5400", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Limpio Grecia", address: "Calle Grecia 1800", materials: "Electrónicos", type: "Privado" },
  ],
  "San Miguel": [
    { name: "Punto Limpio San Miguel", address: "Av. Departamental 4300", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoCentro San Miguel", address: "Calle Santa Rosa 1100", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "GreenPoint San Miguel", address: "Av. Departamental 4400", materials: "Plástico, Metal", type: "Público" },
    { name: "ReciPlus San Miguel", address: "Calle Los Aromos 900", materials: "Electrónicos", type: "Privado" },
    { name: "EcoRecicla San Miguel", address: "Av. Departamental 4500", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Verde San Miguel", address: "Calle Los Aromos 1200", materials: "Plástico, Vidrio", type: "Privado" },
    { name: "Centro Verde San Miguel", address: "Av. Departamental 4600", materials: "Papel, Cartón, Electrónicos", type: "Público" },
    { name: "ReciCentro San Miguel", address: "Calle Los Aromos 1400", materials: "Plástico, Metal", type: "Privado" },
    { name: "EcoPlaza San Miguel", address: "Av. Departamental 4700", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Limpio Los Aromos", address: "Calle Los Aromos 1500", materials: "Electrónicos", type: "Privado" },
  ],
  "Estación Central": [
    { name: "Punto Limpio Estación Central", address: "Av. Central 2200", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoCentro Estación Central", address: "Calle Ecuador 1200", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "GreenPoint Estación Central", address: "Av. Central 2300", materials: "Plástico, Metal", type: "Público" },
    { name: "ReciPlus Estación Central", address: "Calle San Alberto 900", materials: "Electrónicos", type: "Privado" },
    { name: "EcoRecicla Estación Central", address: "Av. Central 2400", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Verde Estación Central", address: "Calle Ecuador 1400", materials: "Plástico, Vidrio", type: "Privado" },
    { name: "Centro Verde Estación Central", address: "Av. Central 2500", materials: "Papel, Cartón, Electrónicos", type: "Público" },
    { name: "ReciCentro Estación Central", address: "Calle San Alberto 1200", materials: "Plástico, Metal", type: "Privado" },
    { name: "EcoPlaza Estación Central", address: "Av. Central 2600", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Limpio Ecuador", address: "Calle Ecuador 1600", materials: "Electrónicos", type: "Privado" },
  ],
  "Conchalí": [
    { name: "Punto Limpio Conchalí", address: "Av. Recoleta 800", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoCentro Conchalí", address: "Calle Las Rosas 900", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "GreenPoint Conchalí", address: "Av. Independencia 1200", materials: "Plástico, Metal", type: "Público" },
    { name: "ReciPlus Conchalí", address: "Calle Los Nogales 700", materials: "Electrónicos", type: "Privado" },
    { name: "EcoRecicla Conchalí", address: "Av. Recoleta 850", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Verde Conchalí", address: "Calle Las Violetas 500", materials: "Plástico, Vidrio", type: "Privado" },
    { name: "Centro Verde Conchalí", address: "Av. Independencia 1300", materials: "Papel, Cartón, Electrónicos", type: "Público" },
    { name: "ReciCentro Conchalí", address: "Calle Los Eucaliptos 1100", materials: "Plástico, Metal", type: "Privado" },
    { name: "EcoPlaza Conchalí", address: "Av. Recoleta 900", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Limpio Las Violetas", address: "Calle Las Violetas 700", materials: "Electrónicos", type: "Privado" },
  ],
  "Cerrillos": [
    { name: "Punto Limpio Cerrillos", address: "Av. Departamental 4100", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoCentro Cerrillos", address: "Calle Los Nogales 1200", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "GreenPoint Cerrillos", address: "Av. Pedro Aguirre Cerda 800", materials: "Plástico, Metal", type: "Público" },
    { name: "ReciPlus Cerrillos", address: "Calle San Nicolás 900", materials: "Electrónicos", type: "Privado" },
    { name: "EcoRecicla Cerrillos", address: "Av. Departamental 4200", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Verde Cerrillos", address: "Calle Los Aromos 1100", materials: "Plástico, Vidrio", type: "Privado" },
    { name: "Centro Verde Cerrillos", address: "Av. Pedro Aguirre Cerda 900", materials: "Papel, Cartón, Electrónicos", type: "Público" },
    { name: "ReciCentro Cerrillos", address: "Calle Los Nogales 1400", materials: "Plástico, Metal", type: "Privado" },
    { name: "EcoPlaza Cerrillos", address: "Av. Departamental 4300", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Limpio Los Aromos", address: "Calle Los Aromos 1200", materials: "Electrónicos", type: "Privado" },
  ],
  "Pedro Aguirre Cerda": [
    { name: "Punto Limpio Pedro Aguirre Cerda", address: "Av. Santa Rosa 3900", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoCentro Pedro Aguirre Cerda", address: "Calle Las Rosas 800", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "GreenPoint Pedro Aguirre Cerda", address: "Av. Santa Rosa 4000", materials: "Plástico, Metal", type: "Público" },
    { name: "ReciPlus Pedro Aguirre Cerda", address: "Calle Los Nogales 900", materials: "Electrónicos", type: "Privado" },
    { name: "EcoRecicla Pedro Aguirre Cerda", address: "Av. Santa Rosa 4100", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Verde Pedro Aguirre Cerda", address: "Calle Los Aromos 1200", materials: "Plástico, Vidrio", type: "Privado" },
    { name: "Centro Verde Pedro Aguirre Cerda", address: "Av. Santa Rosa 4200", materials: "Papel, Cartón, Electrónicos", type: "Público" },
    { name: "ReciCentro Pedro Aguirre Cerda", address: "Calle Las Rosas 1100", materials: "Plástico, Metal", type: "Privado" },
    { name: "EcoPlaza Pedro Aguirre Cerda", address: "Av. Santa Rosa 4300", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Limpio Los Nogales", address: "Calle Los Nogales 1300", materials: "Electrónicos", type: "Privado" },
  ],
  "Cerro Navia": [
    { name: "Punto Limpio Cerro Navia", address: "Av. Cerro Navia 1500", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoCentro Cerro Navia", address: "Calle Los Aromos 900", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "GreenPoint Cerro Navia", address: "Av. Cerro Navia 1600", materials: "Plástico, Metal", type: "Público" },
    { name: "ReciPlus Cerro Navia", address: "Calle Los Robles 1100", materials: "Electrónicos", type: "Privado" },
    { name: "EcoRecicla Cerro Navia", address: "Av. Cerro Navia 1700", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Verde Cerro Navia", address: "Calle Los Olmos 1200", materials: "Plástico, Vidrio", type: "Privado" },
    { name: "Centro Verde Cerro Navia", address: "Av. Cerro Navia 1800", materials: "Papel, Cartón, Electrónicos", type: "Público" },
    { name: "ReciCentro Cerro Navia", address: "Calle Los Aromos 1300", materials: "Plástico, Metal", type: "Privado" },
    { name: "EcoPlaza Cerro Navia", address: "Av. Cerro Navia 1900", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Limpio Los Robles", address: "Calle Los Robles 1400", materials: "Electrónicos", type: "Privado" },
  ],
  "Pudahuel": [
    { name: "Punto Limpio Pudahuel", address: "Av. Teniente Cruz 5000", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoCentro Pudahuel", address: "Calle Las Palmas 1200", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "GreenPoint Pudahuel", address: "Av. Central 5200", materials: "Plástico, Metal", type: "Público" },
    { name: "ReciPlus Pudahuel", address: "Calle Los Robles 1100", materials: "Electrónicos", type: "Privado" },
    { name: "EcoRecicla Pudahuel", address: "Av. Teniente Cruz 5300", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Verde Pudahuel", address: "Calle Las Palmas 1400", materials: "Plástico, Vidrio", type: "Privado" },
    { name: "Centro Verde Pudahuel", address: "Av. Central 5400", materials: "Papel, Cartón, Electrónicos", type: "Público" },
    { name: "ReciCentro Pudahuel", address: "Calle Los Aromos 1200", materials: "Plástico, Metal", type: "Privado" },
    { name: "EcoPlaza Pudahuel", address: "Av. Teniente Cruz 5500", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Limpio Las Palmas", address: "Calle Las Palmas 1600", materials: "Electrónicos", type: "Privado" },
  ],
  "San Bernardo": [
    { name: "Punto Limpio San Bernardo", address: "Av. San Bernardo 3200", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoCentro San Bernardo", address: "Calle Los Nogales 1200", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "GreenPoint San Bernardo", address: "Av. Colón 2100", materials: "Plástico, Metal", type: "Público" },
    { name: "ReciPlus San Bernardo", address: "Calle Maipú 900", materials: "Electrónicos", type: "Privado" },
    { name: "EcoRecicla San Bernardo", address: "Av. San Bernardo 3300", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Verde San Bernardo", address: "Calle Los Aromos 1100", materials: "Plástico, Vidrio", type: "Privado" },
    { name: "Centro Verde San Bernardo", address: "Av. Colón 2300", materials: "Papel, Cartón, Electrónicos", type: "Público" },
    { name: "ReciCentro San Bernardo", address: "Calle Maipú 1200", materials: "Plástico, Metal", type: "Privado" },
    { name: "EcoPlaza San Bernardo", address: "Av. San Bernardo 3400", materials: "Papel, Cartón", type: "Público" },
    { name: "Punto Limpio Los Nogales", address: "Calle Los Nogales 1300", materials: "Electrónicos", type: "Privado" },
  ],
  "El Bosque": [
    { name: "Punto Limpio El Bosque", address: "Av. El Bosque 1200", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoCentro El Bosque", address: "Calle Los Aromos 900", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "GreenPoint El Bosque", address: "Av. Los Libertadores 1500", materials: "Plástico, Metal", type: "Público" },
    { name: "ReciPlus El Bosque", address: "Calle Los Robles 1100", materials: "Electrónicos", type: "Privado" },
    { name: "EcoRecicla El Bosque", address: "Av. El Bosque 1300", materials: "Papel, Cartón", type: "Público" },
  ],
  "La Cisterna": [
    { name: "Punto Limpio La Cisterna", address: "Av. Santa Rosa 3200", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoCentro La Cisterna", address: "Calle Los Nogales 1200", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "GreenPoint La Cisterna", address: "Av. Lo Ovalle 2100", materials: "Plástico, Metal", type: "Público" },
    { name: "ReciPlus La Cisterna", address: "Calle San Jorge 900", materials: "Electrónicos", type: "Privado" },
    { name: "EcoRecicla La Cisterna", address: "Av. Santa Rosa 3300", materials: "Papel, Cartón", type: "Público" },
  ],
  "La Pintana": [
    { name: "Punto Limpio La Pintana", address: "Av. Gabriela 4500", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoCentro La Pintana", address: "Calle Los Aromos 1200", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "GreenPoint La Pintana", address: "Av. Santa Rosa 4600", materials: "Plástico, Metal", type: "Público" },
    { name: "ReciPlus La Pintana", address: "Calle Los Robles 900", materials: "Electrónicos", type: "Privado" },
    { name: "EcoRecicla La Pintana", address: "Av. Gabriela 4700", materials: "Papel, Cartón", type: "Público" },
  ],
  "Paine": [
    { name: "Punto Limpio Paine", address: "Av. Chile 120", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoCentro Paine", address: "Calle Los Álamos 50", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "GreenPoint Paine", address: "Av. O'Higgins 90", materials: "Plástico, Metal", type: "Público" },
    { name: "ReciPlus Paine", address: "Calle Las Rosas 30", materials: "Electrónicos", type: "Privado" },
    { name: "EcoRecicla Paine", address: "Av. Chile 150", materials: "Papel, Cartón", type: "Público" },
  ],
  "Pirque": [
    { name: "Punto Limpio Pirque", address: "Av. Gran Avenida 150", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoCentro Pirque", address: "Calle Los Nogales 50", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "GreenPoint Pirque", address: "Av. Las Vizcachas 120", materials: "Plástico, Metal", type: "Público" },
    { name: "ReciPlus Pirque", address: "Calle El Principal 30", materials: "Electrónicos", type: "Privado" },
    { name: "EcoRecicla Pirque", address: "Av. Gran Avenida 180", materials: "Papel, Cartón", type: "Público" },
  ],
  "Talagante": [
    { name: "Punto Limpio Talagante", address: "Av. O'Higgins 800", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoCentro Talagante", address: "Calle Los Robles 200", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "GreenPoint Talagante", address: "Av. Libertador Bernardo O'Higgins 900", materials: "Plástico, Metal", type: "Público" },
    { name: "ReciPlus Talagante", address: "Calle Los Álamos 150", materials: "Electrónicos", type: "Privado" },
    { name: "EcoRecicla Talagante", address: "Av. O'Higgins 850", materials: "Papel, Cartón", type: "Público" },
  ],
  "Melipilla": [
    { name: "Punto Limpio Melipilla", address: "Av. Manuel Rodríguez 1200", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoCentro Melipilla", address: "Calle Los Robles 300", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "GreenPoint Melipilla", address: "Av. Arturo Prat 1500", materials: "Plástico, Metal", type: "Público" },
    { name: "ReciPlus Melipilla", address: "Calle Los Álamos 400", materials: "Electrónicos", type: "Privado" },
    { name: "EcoRecicla Melipilla", address: "Av. Manuel Rodríguez 1300", materials: "Papel, Cartón", type: "Público" },
  ],
  "San Joaquín": [
    { name: "Punto Limpio San Joaquín", address: "Av. Vicuña Mackenna 3800", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoCentro San Joaquín", address: "Calle Los Aromos 1200", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "GreenPoint San Joaquín", address: "Av. Pedro Aguirre Cerda 3900", materials: "Plástico, Metal", type: "Público" },
    { name: "ReciPlus San Joaquín", address: "Calle Los Robles 900", materials: "Electrónicos", type: "Privado" },
    { name: "EcoRecicla San Joaquín", address: "Av. Vicuña Mackenna 4000", materials: "Papel, Cartón", type: "Público" },
  ],
  "San Ramón": [
    { name: "Punto Limpio San Ramón", address: "Av. Santa Rosa 5000", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoCentro San Ramón", address: "Calle Los Nogales 1300", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "GreenPoint San Ramón", address: "Av. Santa Rosa 5100", materials: "Plástico, Metal", type: "Público" },
    { name: "ReciPlus San Ramón", address: "Calle Los Robles 1100", materials: "Electrónicos", type: "Privado" },
    { name: "EcoRecicla San Ramón", address: "Av. Santa Rosa 5200", materials: "Papel, Cartón", type: "Público" },
  ],
  "Padre Hurtado": [
    { name: "Punto Limpio Padre Hurtado", address: "Av. Gran Avenida 100", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoCentro Padre Hurtado", address: "Calle Los Álamos 50", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "GreenPoint Padre Hurtado", address: "Av. O'Higgins 120", materials: "Plástico, Metal", type: "Público" },
    { name: "ReciPlus Padre Hurtado", address: "Calle El Principal 30", materials: "Electrónicos", type: "Privado" },
    { name: "EcoRecicla Padre Hurtado", address: "Av. Gran Avenida 150", materials: "Papel, Cartón", type: "Público" },
  ],
  "Tiltil": [
    { name: "Punto Limpio Tiltil", address: "Av. Tiltil 100", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoCentro Tiltil", address: "Calle Los Robles 50", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "GreenPoint Tiltil", address: "Av. Tiltil 120", materials: "Plástico, Metal", type: "Público" },
    { name: "ReciPlus Tiltil", address: "Calle Los Álamos 30", materials: "Electrónicos", type: "Privado" },
    { name: "EcoRecicla Tiltil", address: "Av. Tiltil 150", materials: "Papel, Cartón", type: "Público" },
  ],
  "Lampa": [
    { name: "Punto Limpio Lampa", address: "Av. Lampa 200", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoCentro Lampa", address: "Calle Los Álamos 100", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "GreenPoint Lampa", address: "Av. Lampa 220", materials: "Plástico, Metal", type: "Público" },
    { name: "ReciPlus Lampa", address: "Calle Los Robles 50", materials: "Electrónicos", type: "Privado" },
    { name: "EcoRecicla Lampa", address: "Av. Lampa 250", materials: "Papel, Cartón", type: "Público" },
  ],
  "María Pinto": [
    { name: "Punto Limpio María Pinto", address: "Av. Principal 50", materials: "Papel, Cartón, Plástico", type: "Público" },
    { name: "EcoCentro María Pinto", address: "Calle Los Nogales 30", materials: "Vidrio, Plástico", type: "Privado" },
    { name: "GreenPoint María Pinto", address: "Av. Principal 70", materials: "Plástico, Metal", type: "Público" },
    { name: "ReciPlus María Pinto", address: "Calle Los Álamos 20", materials: "Electrónicos", type: "Privado" },
    { name: "EcoRecicla María Pinto", address: "Av. Principal 100", materials: "Papel, Cartón", type: "Público" },
  ],
};

export const comunas = Object.keys(comunaPoints);

// Approximate center coordinates for each comuna (Región Metropolitana, Chile)
export const comunaCenters: Record<string, { lat: number; lng: number }> = {
  "Santiago": { lat: -33.4489, lng: -70.6693 },
  "Providencia": { lat: -33.4263, lng: -70.6111 },
  "Las Condes": { lat: -33.4106, lng: -70.5680 },
  "Maipú": { lat: -33.5110, lng: -70.7580 },
  "Ñuñoa": { lat: -33.4566, lng: -70.5965 },
  "La Florida": { lat: -33.5226, lng: -70.5980 },
  "Puente Alto": { lat: -33.6110, lng: -70.5750 },
  "Peñalolén": { lat: -33.4880, lng: -70.5440 },
  "Quilicura": { lat: -33.3640, lng: -70.7290 },
  "Huechuraba": { lat: -33.3700, lng: -70.6390 },
  "Renca": { lat: -33.4040, lng: -70.7290 },
  "Lo Prado": { lat: -33.4450, lng: -70.7220 },
  "Lo Barnechea": { lat: -33.3500, lng: -70.5170 },
  "Vitacura": { lat: -33.3900, lng: -70.5800 },
  "Independencia": { lat: -33.4150, lng: -70.6660 },
  "Recoleta": { lat: -33.4030, lng: -70.6420 },
  "La Granja": { lat: -33.5380, lng: -70.6280 },
  "Macul": { lat: -33.4860, lng: -70.5990 },
  "San Miguel": { lat: -33.4960, lng: -70.6510 },
  "Estación Central": { lat: -33.4570, lng: -70.6920 },
  "Conchalí": { lat: -33.3830, lng: -70.6760 },
  "Cerrillos": { lat: -33.4970, lng: -70.7110 },
  "Pedro Aguirre Cerda": { lat: -33.4870, lng: -70.6760 },
  "Cerro Navia": { lat: -33.4220, lng: -70.7370 },
  "Pudahuel": { lat: -33.4400, lng: -70.7660 },
  "San Bernardo": { lat: -33.5930, lng: -70.7030 },
  "El Bosque": { lat: -33.5610, lng: -70.6760 },
  "La Cisterna": { lat: -33.5340, lng: -70.6630 },
  "La Pintana": { lat: -33.5830, lng: -70.6390 },
  "Paine": { lat: -33.8090, lng: -70.7390 },
  "Pirque": { lat: -33.6390, lng: -70.5550 },
  "Talagante": { lat: -33.6640, lng: -70.9270 },
  "Melipilla": { lat: -33.6890, lng: -71.2160 },
  "San Joaquín": { lat: -33.4960, lng: -70.6280 },
  "San Ramón": { lat: -33.5380, lng: -70.6450 },
  "Padre Hurtado": { lat: -33.5740, lng: -70.8170 },
  "Tiltil": { lat: -33.0830, lng: -70.9320 },
  "Lampa": { lat: -33.2860, lng: -70.8770 },
  "María Pinto": { lat: -33.5470, lng: -71.1090 },
};

export interface ComunaMapPoint {
  id: string;
  name: string;
  address: string;
  materials: string[];
  type: "Público" | "Privado";
  comuna: string;
  latitude: number;
  longitude: number;
}

// Deterministic small offset so points don't overlap (~150-400m around center)
function offsetFor(seed: string): { dLat: number; dLng: number } {
  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (h * 31 + seed.charCodeAt(i)) | 0;
  const a = ((h & 0xffff) / 0xffff) * 2 - 1;
  const b = (((h >> 16) & 0xffff) / 0xffff) * 2 - 1;
  return { dLat: a * 0.006, dLng: b * 0.006 };
}

export function getAllComunaMapPoints(): ComunaMapPoint[] {
  const out: ComunaMapPoint[] = [];
  for (const comuna of comunas) {
    const center = comunaCenters[comuna];
    if (!center) continue;
    for (const p of comunaPoints[comuna]) {
      const { dLat, dLng } = offsetFor(`${comuna}-${p.name}-${p.address}`);
      out.push({
        id: `${comuna}-${p.name}`,
        name: p.name,
        address: p.address,
        materials: p.materials.split(",").map((m) => m.trim()).filter(Boolean),
        type: p.type,
        comuna,
        latitude: center.lat + dLat,
        longitude: center.lng + dLng,
      });
    }
  }
  return out;
}
